# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Interaction' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Interaction
    pod 'Parse'
    pod 'ParseUI'
    pod 'Discovery', '~> 1.1'


  target 'InteractionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InteractionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
