# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'InSync' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InSync
    pod 'Parse'
    pod 'ParseUI'
    pod 'VideoSplashKit'
    pod 'Onboard'
    pod 'Alamofire', '~> 3.4'
    pod 'AFNetworking'
    pod 'EZSwipeController'
    pod 'GSKStretchyHeaderView'
    pod 'StretchHeader'
    pod 'MEVFloatingButton'
    pod 'NVActivityIndicatorView'
    pod 'Pages'
    pod 'PageMenu'
    pod 'CircleProgressBar', '~> 0.31’
    pod 'BubbleTransition', '~> 1.0.0'
    pod 'MGSwipeTableCell'
    pod 'MarqueeLabel/Swift'
    pod 'BFRadialWaveView', '~> 1.4'
    pod 'SwiftSiriWaveformView', '~> 0.0'
    pod 'ESTMusicIndicator', '~> 0.1'
    pod 'Shimmer', '~> 1.0'
    pod 'MNFloatingActionButton', '~> 0.1'
    pod 'BAFluidView', '~> 0.2'
    pod 'XLPagerTabStrip', '~> 5.0'
    pod 'Whisper'
    pod 'Toast-Swift', '~> 1.3.0'
    pod 'Gecco'
    pod 'AudioKit', '~> 3.1'
    pod 'CBZSplashView', '~> 1.0.0'

end
